# Cloud Build configuration for Variant Analytics Dashboard (Dash Version)
# Uses the same service account as the Streamlit version

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/variant-dashboard-dash:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/variant-dashboard-dash:latest'
      - '.'

  # Push the container images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/variant-dashboard-dash:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/variant-dashboard-dash:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'variant-dashboard-dash'
      - '--image'
      - 'gcr.io/$PROJECT_ID/variant-dashboard-dash:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '20'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '5'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      # Use the SAME service account as Streamlit version
      - '--service-account'
      - 'variant-dashboard-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCS_CACHE_BUCKET=variant-dashboard-cache-$PROJECT_ID'
      - '--cpu-boost'
      - '--no-cpu-throttling'

images:
  - 'gcr.io/$PROJECT_ID/variant-dashboard-dash:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/variant-dashboard-dash:latest'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
